# ░██████░░███████░░█████░░░██████░░
# ░██░░░░░░░░██░░░░██░░░██░░██░░░██░  READ THIS BEFORE USING IT.
# ░██████░░░░██░░░░██░░░██░░██████░░  SEE NOTES BELOW:
# ░░░░░██░░░░██░░░░██░░░██░░██░░░░░░
# ░██████░░░░██░░░░░████░░░░██░░░░░░
# You will hit issues if any of these are set to the wrong value.
# Please read each line of this file before starting the server.
# 
#  =============================================================================
#
# Self hosting users can safely delete this (a new key will be created).
# This key is used to exchange secrets between bots and MQTT servers (important
# if you don't use SSL)
# SERVER WONT WORK IF YOU DONT CHANGE THIS:
RSA_KEY: "Change this! Keys look like `-----BEGIN RSA .........`"
# If you use Let's Encrypt for SSL,
# you must set this when renewing SSL.
# Otherwise, not required and CAN BE REMOVED.
ACME_SECRET: "-----"
# If your server is on a domain (eg: my-own-farmbot.com), put it here.
# 0.0.0.0 is a good value because it exposes all IPs on your machine.
API_HOST: "0.0.0.0"
# 3000 for local development. 443 is using SSL. You will need `sudo` to use PORT
# 80 on most systems.
API_PORT: "3000"
# This can be set to anything. Most users can just delet it.
DOCS: "Set this to any value if you want to generate API docs after running tests"
# Most users can delete this.
DATABASE_URL: "postgres://USERNAME:PASSWORD@URL:PORT/DB_NAME"
# See note below.
DEVISE_SECRET: "Used for devise. Use `rake secret` to generate a new value."
# Most personal server users can delete this.
FORCE_SSL: "Remove this if not using HTTPS://"
# Firmware update server. Use default if you don't have a special use case.
# Off grid servers may have issues connecting to our update URL.
FW_UPDATE_SERVER: "https://api.github.com/repos/FarmBot/farmbot-arduino-firmware/releases/latest"
OS_UPDATE_SERVER: "https://api.github.com/repos/farmbot/farmbot_os/releases/latest"
# Google Cloud Storage API Bucket for image data. Deleting this will save to disk
GCS_BUCKET: "GOOGLE_CLOUD_STORAGE_BUCKET_NAME_FOR_IMAGE_FILES"
# Google Cloud Storage ID for image data. Deleting this will save images to disk.
GCS_ID: "GOOGLE_CLOUD_STORAGE: 'interop' id"
GCS_KEY: "GOOGLE_CLOUD_STORAGE: 'interop' key"
# Most users can delete this.
HEROKU_SLUG_COMMIT: "This is set by Herok, used by Frontend to show current version."
# Where is your MQTT server running? Leave as 0.0.0.0 if it is on the same machine.
MQTT_HOST: "0.0.0.0"
# You can delete this if you don't work for FarmBot, Inc. It's our production
# error handler.
NPM_ADDON: "Used by FarmBot, Inc. to load proprietary extras, like Rollbar."
# Same as above. Can be deleted unless you are a Rollbar.IO customer.
ROLLBAR_ACCESS_TOKEN: "____"
SENDGRID_PASSWORD: "Used by FarmBot, Inc"
SENDGRID_USERNAME: "Used by FarmBot, Inc"
# For email delivery.
SMTP_HOST: "smtp.sendgrid.net"
# Optional with default of 587
SMTP_PORT: 587
